### ISSUE TITLE
Cookies filter problem with 'localhost'

### ISSUE THREAD

**Issue by Muffo** [bigspaceship/Clear-Cache-Extension#3]
I'm not able to set the filter to remove only the cookies from http://localhost
When I write 'localhost' in the textbox the background remains red.

I guess that the problem is caused by the lack of dots (.) in the URL.

**Comment by benjaminbojko** [comment]
Thanks for your feedback. I'll get to solving this issue as soon as I have some more free time. Cookie-domain syntax is a little finicky and I remember it being tricky to get this running properly. I'll see what I can do.

**Comment by Muffo** [comment]
For the moment I've found a workaround.
Instead of using 'localhost' I use 127.0.0.1 and everything works great.

**Comment by benjaminbojko** [comment]
That's good to know! Hopefully I'll get around to addressing a few issues and feature requests for the extension this weekend.

**Comment by benjaminbojko** [comment]
I just updated the extension in the WebStore to 0.3.3.0. You can either wait for an automatic update or go to the Extensions settings page and update manually. Please let me know if you still run into issues.

**Comment by Muffo** [comment]
Great! Thank you very much. Now I can do everything with just one button :)
