### ISSUE TITLE
sessionStorage

### ISSUE THREAD

**Issue by Rycochet** [bigspaceship/Clear-Cache-Extension#4]
I've come across a situation where I'm wanting to clear the sessionStorage, but leave localStorage alone, hoping that it's worth adding.

**Comment by joewanko** [comment]
@Rycochet, unfortunately I do not believe that the API provides us the ability to manipulate the sessionStorage data.

See here: https://developer.chrome.com/extensions/browsingData

**Comment by Rycochet** [comment]
Drat, would need code to be run on the page itself and the extra permissions that would entail giving (even with the source freely available, giving a privacy tool the ability to read your data on all websites sounds bad lol)... I guess I'll stick to "sessionStorage.clear()" in the console for now ;-)
